/*
 * Regenerates third-party/three.js and third-party/three-addons.js from the
 * npm package "three" (devDependency), with esbuild.
 *
 *   npm install            # brings the version pinned in package.json
 *   node tools/three/build-three.js
 *
 * WHY: since r186, build/three.cjs is no longer a CommonJS build but a
 * two-line shim (require(esm) of three.module.js) meant for Node >= 22.
 * Jocly loads three.js in the browser through BrowserScriptLoader.import(),
 * which evaluates the file as `(function(exports){ ... })({})` -- so a real
 * self-contained script that fills `exports` has to be produced here.
 *
 * The addons (GLTFLoader, BufferGeometryUtils, FontLoader, TextGeometry) are
 * bundled the same way from examples/jsm, their `import ... from "three"`
 * being redirected to the global THREE that jocly.game.js sets up. This
 * replaces the hand-adapted r150 copies that lagged 35 releases behind the
 * core.
 */
const esbuild = require("esbuild");
const path = require("path");
const fs = require("fs");

const ROOT = path.join(__dirname, "..", "..");
const THREE_DIR = path.join(ROOT, "node_modules", "three");
const version = require(path.join(THREE_DIR, "package.json")).version;
const banner = "/* three.js " + version + " (r" + version.split(".")[1] +
	") - MIT - regenerated by tools/three/build-three.js, do not edit */";

// 1. core: IIFE whose namespace is copied into the `exports` object that
//    BrowserScriptLoader hands in (or onto window.THREE if loaded bare)
esbuild.buildSync({
	entryPoints: [path.join(THREE_DIR, "build/three.module.js")],
	bundle: true,
	format: "iife",
	globalName: "__jocly_three",
	target: "es2020",
	legalComments: "inline",
	banner: { js: banner },
	footer: { js:
		"if(typeof exports===\"object\"&&exports)Object.assign(exports,__jocly_three);" +
		"else if(typeof window!==\"undefined\"&&!window.THREE)window.THREE=__jocly_three;" },
	outfile: path.join(ROOT, "third-party/three.js"),
});

// 2. addons: "three" -> global THREE
const threeGlobal = {
	name: "three-global",
	setup(build) {
		build.onResolve({ filter: /^three$/ }, () => ({ path: "three", namespace: "three-global" }));
		build.onLoad({ filter: /.*/, namespace: "three-global" }, () => ({
			contents: "module.exports = THREE;", loader: "js" }));
	},
};
const entry = `
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import * as BufferGeometryUtils from "three/examples/jsm/utils/BufferGeometryUtils.js";
import { FontLoader, Font } from "three/examples/jsm/loaders/FontLoader.js";
import { TextGeometry } from "three/examples/jsm/geometries/TextGeometry.js";
THREE.GLTFLoader = GLTFLoader;
THREE.BufferGeometryUtils = BufferGeometryUtils;
THREE.FontLoader = FontLoader;
THREE.Font = Font;
THREE.TextGeometry = TextGeometry;
`;
esbuild.build({
	stdin: { contents: entry, resolveDir: ROOT, sourcefile: "three-addons-entry.js" },
	bundle: true,
	format: "iife",
	target: "es2020",
	legalComments: "inline",
	banner: { js: banner.replace("three.js", "three.js addons") },
	plugins: [threeGlobal],
	outfile: path.join(ROOT, "third-party/three-addons.js"),
}).then(function () {
	console.log("three " + version + " -> third-party/three.js, third-party/three-addons.js");
}, function () { process.exit(1); });
